### PR TITLE
creating a copy of routes.rb is bad

### PR DESCRIPTION
**Pull request by ch1ago**
let us create a fingerprint file instead

### CODE REVIEW

**Comment by ch1ago** [comment]
BTW cool gem, I had been looking for something like this for months :)

**Comment by ch1ago** [comment]
@bcaccinolo  ping!

**Comment by bcaccinolo** [comment]
Hey James, sorry for the late reply. Your proposal is nice. Let me check this cause it's not a well maintained gem.

**Comment by ch1ago** [comment]
@bcaccinolo ping!

**Pull request closed without merging**
